name: hydro
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.10
  - matplotlib-inline=0.1.6
  - pip=24.2
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - ipykernel=6.29.5
  - pip:
    - pysheds==0.4
    - numpy==1.26.4
    - pandas==2.2.3
    - geopandas==1.0.1
    - rasterio==1.4.1
    - matplotlib==3.9.2
    - shapely==2.0.6
    - pyproj==3.7.0
    - scikit-image==0.24.0
    - scipy==1.14.1
    - numba==0.60.0
    - flask==3.0.3
    - flask-cors==5.0.0
